export const IRAN_ROLE_IDS = [
  'supreme-leader',
  'president',
  'chief-justice',
  'parliament-speaker',
  'snsc-secretary',
  'irgc-commander',
  'chief-of-general-staff',
  'defense-minister',
  'intelligence-minister',
  'foreign-minister',
  'first-vp',
  'army-commander',
  'irgc-quds-commander',
  'basij-commander',
] as const;

export const UNITED_STATES_ROLE_IDS = [
  'president',
  'vice-president',
  'secretary-of-war',
  'secretary-of-state',
  'national-security-advisor',
  'dni',
  'chairman-jcs',
  'secretary-of-homeland-security',
  'deputy-secretary-of-war',
  'deputy-secretary-of-state',
  'cia-director',
  'vice-chairman-jcs',
  'centcom-commander',
  'northcom-commander',
  'deputy-secretary-of-homeland-security',
] as const;

export const ISRAEL_ROLE_IDS = [
  'prime-minister',
  'president',
  'security-cabinet',
  'defense-minister',
  'foreign-minister',
  'nsc-head',
  'mossad-director',
  'shin-bet-director',
  'idf-chief-of-staff',
  'pm-military-secretary',
  'mod-director-general',
  'cyber-directorate-head',
  'air-force-commander',
  'aman-chief',
] as const;

export const HEZBOLLAH_ROLE_IDS = [
  'secretary-general',
  'deputy-secretary-general',
  'shura-council',
  'parliamentary-council-head',
  'executive-council-head',
  'jihad-council',
  'liaison-coordination-head',
  'intelligence-headquarters-head',
  'southern-command',
] as const;

export const IRGC_ROLE_IDS = [
  'irgc-commander',
  'deputy-irgc-commander',
  'irgc-ground-forces-commander',
  'irgc-aerospace-commander',
  'irgc-navy-commander',
  'irgc-quds-commander',
  'basij-commander',
  'irgc-intelligence-chief',
  'sarallah-headquarters-chief',
  'tehran-provincial-unit-chief',
  'irgc-spokesperson',
] as const;
